# 策略
### 0.实现工具
scikit-learn
### 1.数据特征
特征数量少，样本数量正常
### 2.实现方法
由于确定数据的特征空间分布，先使用线性核函数实现，观察误差
然后再使用RBF核函数实现
### 3.后期扩展
深入了解SVM的理论推导，最好是自己推导一遍；

尝试更多的核函数以及参数，考虑这些函数的融合；

实现可视化

### resouce
[SVM分类方案](https://www.cnblogs.com/CheeseZH/p/5265959.html)

[SVM核函数](https://blog.csdn.net/batuwuhanpei/article/details/52354822)

[SVM概括](https://www.cnblogs.com/hhh5460/p/5186197.html)

[SVM example](http://scikit-learn.org/stable/modules/svm.html#svm)

[SVM API](http://scikit-learn.org/stable/modules/classes.html)

In [1]:
from sklearn import svm
import pandas as pd
import numpy as np

In [2]:
train_set_num = 35000
test_set_num = 15000
batch_size = 500
iteration = int(train_set_num / batch_size) #　这个地方注意一下

In [3]:
# extract data from the file and store it in the dataframe
def extract_data(filename):
    data = pd.read_table(filename, delim_whitespace = True)
    # handle the exception
    #shuffle 
    data = data.sample(frac = 1).reset_index(drop = True)
    
    # seperate the dataset
    # train/test = 7/3
    train_set = data[0:train_set_num]
    test_set = data[train_set_num:]
    return train_set, test_set

# seperate the data and label
# return the ndarray
def split_data_label(data):
    data_label = data.as_matrix(['Label'])
    data_input = data.as_matrix(['K1', 'K2', 'K3', 'K4'])
    print(data_label)
    print(data_input)
    return data_input, data_label

# next_batch operation
start = 0
def next_batch(data_input, data_label, batch_size, set_num):
    global start
    begin = start
    end = begin + batch_size
    # better improve this part
    if end >= set_num:
        print("This set is done")
    start = end
    return data_input[begin:end, : ], data_label[begin:end, : ]

shuffle:https://blog.csdn.net/qq_22238533/article/details/70917102

slice:https://blog.csdn.net/yoonhee/article/details/76168253

In [4]:
filename = "/home/rick/Documents/data/CB550_features_targets.dat"
train_set, test_set = extract_data(filename)
train_input, train_label = split_data_label(train_set)
test_input, test_label = split_data_label(test_set)

[[2]
 [2]
 [3]
 ..., 
 [4]
 [3]
 [4]]
[[ 0.81371   0.12782   0.341892  0.482992]
 [ 0.815671  0.124409  0.333252  0.481774]
 [ 0.856028  0.057183  0.853342  0.850068]
 ..., 
 [ 0.833912  0.147872  0.424807  0.591576]
 [ 0.843921  0.057066  0.843098  0.870593]
 [ 0.734954  0.133678  0.374875  0.522709]]
[[2]
 [4]
 [5]
 ..., 
 [3]
 [2]
 [4]]
[[ 0.924276  0.141772  0.376967  0.548982]
 [ 0.750879  0.132924  0.384267  0.523133]
 [ 0.848536  0.913257  0.461573  0.867726]
 ..., 
 [ 0.970383  0.064324  0.94786   0.974653]
 [ 0.862743  0.131835  0.346604  0.504342]
 [ 0.751375  0.132033  0.382824  0.525644]]


In [5]:
clf = svm.SVC(decision_function_shape = 'ovo')

for i in range(iteration):
        batch_X, batch_Y = next_batch(train_input, train_label, batch_size, train_set_num)
        clf.fit(batch_X, batch_Y.T.ravel())


'''
def run(input, label ,batch_size, set_num):
    # 注意python３取消了xrange()
    for i in range(iteration):
        batch_X, batch_Y = next_batch(input, label, batch_size, set_num)
        clf.fit(batch_X, batch_Y.T.ravel())

run(train_input, train_label, batch_size, train_set_num)
'''

This set is done


'\ndef run(input, label ,batch_size, set_num):\n    # 注意python３取消了xrange()\n    for i in range(iteration):\n        batch_X, batch_Y = next_batch(input, label, batch_size, set_num)\n        clf.fit(batch_X, batch_Y.T.ravel())\n\nrun(train_input, train_label, batch_size, train_set_num)\n'

In [6]:
result = clf.predict(test_input)
test_label = test_label
#print(test_label)
#print(result)
num = len(result)
bingo = 0
for i in range(num - 1):
    if result[i] == test_label[i][0]:
        bingo += 1
accuracy = bingo / num
print("the accuracy of precition is %f"% accuracy)

the accuracy of precition is 0.797400
